[package]
name = "wasi-tests"
version = "0.1.0"
authors = ["Oasis Labs <feedback@oasislabs.com>"]
edition = "2018"

[dependencies]
base64 = "0.11"
libc = "0.2"

[workspace]

[profile.release]
incremental = false
lto = true
opt-level = "z"
panic = "abort"
