[package]
description = "Ethcore network library"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "ethcore-network"
version = "1.12.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
error-chain = { version = "0.10", default-features = false }
ethcore-crypto = { path = "../../ethcore/crypto" }
ethcore-io = { path = "../io" }
ethereum-types = { git = "https://github.com/oasislabs/primitives", branch = "ekiden" }
ethkey = { path = "../../ethkey" }
ipnetwork = "0.12.6"
rlp = { path = "../rlp" }
libc = "0.2"
snappy = { git = "https://github.com/paritytech/rust-snappy" }


[dev-dependencies]
assert_matches = "1.2"
