version: 2
jobs:
  build:
    docker:
      - image: oasislabs/testing:0.3.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: xlarge
    steps:
      # Check out source from github
      - checkout

      - run:
          name: Checkstyle
          command: cargo fmt -p ethcore -p ethcore-transaction -p ethkey -p vm -p wasm -- --check

      - run:
          name: Check out git submodules (wasm-tests, in particular)
          command: git submodule update --init

      # Build ethcore for runtime (SGX)
      - run:
          name: Build ethcore for runtime (SGX)
          working_directory: ethcore
          command: cargo build --target x86_64-fortanix-unknown-sgx

      # Build ethcore for gateway
      - run:
          name: Build ethcore for gateway
          working_directory: ethcore
          command: cargo build

      # Build other gateway dependencies
      - run:
          name: Build other gateway dependencies
          command: cargo build --package mem --package parity-reactor --package parity-rpc --package path

      # Test ethcore
      - run:
          name: Run ethcore tests
          command: cargo test --package ethcore --package ethcore-transaction --package ethkey --package vm --package wasm --features "ethkey-test"
