version: 2


jobs:
  build:
    docker:
      - image: oasislabs/testing:0.3.0
    resource_class: xlarge
    steps:
      # Check out source from github
      - checkout

      - run:
          name: Checkstyle
          command: cargo fmt -p ethcore -p ethcore-transaction -p ethkey -p vm -p wasm -- --check

      # Build ethcore for runtime (SGX)
      - run:
          name: Build ethcore for runtime (SGX)
          working_directory: ethcore
          command: cargo build --target x86_64-fortanix-unknown-sgx

      # Build ethcore for gateway
      - run:
          name: Build ethcore for gateway
          working_directory: ethcore
          command: cargo build

      # Build other gateway dependencies
      - run:
          name: Build other gateway dependencies
          command: cargo build --package mem --package parity-reactor --package parity-rpc

      # Run cargo tests
      - run:
          name: Run cargo tests
          command: cargo test --package ethcore --package ethcore-transaction --package ethkey --package vm --package wasm --features "ethkey-test"

  coverage:
    machine: true
    steps:
      - checkout
      - run:
          name: Tarpaulin code coverage
          command: docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin cargo tarpaulin --ciserver circle-ci --coveralls $COVERALLS_REPO_TOKEN --ignore-tests -p ethcore -p ethcore-transaction -p ethkey -p vm -p wasm --features "ethkey-test"


workflows:
  version: 2

  main:
    jobs:
      - build
      - coverage
