version: 2
jobs:
  build:
    docker:
      - image: ekiden/testing:0.2.0
    resource_class: xlarge
    steps:
      # Check out source from github
      - checkout

      # Build ethcore (runtime)
      - run:
          name: Build ethcore for runtime
          working_directory: ethcore
          command: RUST_TARGET_PATH=$(pwd) RUSTFLAGS="-Z force-unstable-if-unmarked" xargo build --target x86_64-unknown-linux-sgx --release

      # Build ethcore (gateway)
      - run:
          name: Build ethcore for gateway
          working_directory: ethcore
          command: cargo build --features "gateway"

      # Test ethcore
      - run:
          name: Run the ethcore tests
          working_directory: ethcore
          command: cargo test
