[package]
name = "ethjson"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
ethereum-types = { git = "https://github.com/oasislabs/primitives", branch = "ekiden" }
rustc-hex = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

