[package]
name = "hashdb"
version = "0.1.1"
authors = ["Parity Technologies <admin@parity.io>"]
description = "trait for hash-keyed databases."
license = "GPL-3.0"

[dependencies]
elastic-array = "0.10"
ethereum-types = { version = "0.3", default-features = false, features = ["std", "serialize"] }
